export const ResponseStatus: Record<number, string> = {
    // Informational Responses (100 – 199)
    100: 'The client should continue with its request.',
    101: 'The server is switching protocols.',
    102: 'The server has received and is processing the request.',
    103: 'The server is sending early hints to preload resources.',
    // Successful Responses (200 – 299)
    200: 'The request was successful.',
    201: 'The request was successful and a new resource was created.',
    202: 'The request has been accepted but not yet processed.',
    203: 'The request was successful, but the information may not be from the origin server.',
    204: 'The request was successful, but there is no content to return.',
    205: 'The client should reset the document view.',
    206: 'The server is delivering only part of the resource.',
    207: "Multiple independent operations' statuses.",
    208: 'The resource has already been reported.',
    226: 'The server has fulfilled the request using instance manipulations.',
    // Redirection Messages (300 – 399)
    300: 'There are multiple options for the resource.',
    301: 'The resource has been moved to a new permanent URI.',
    302: 'The resource is temporarily available at a different URI.',
    303: 'The client should retrieve the resource from a different URI.',
    304: 'The resource has not been modified since the last request.',
    305: '(Deprecated) The resource must be accessed via a proxy.',
    307: 'The resource is temporarily available at a different URI, but the method must remain unchanged.',
    308: 'The resource has been moved permanently to a new URI.',
    // Client Error Responses (400 – 499)
    400: 'The request cannot be processed due to client error.',
    401: 'Authentication is required and has failed or has not been provided.',
    402: 'Payment is required to process the request.',
    403: 'The server refuses to authorize the request.',
    404: 'The requested resource could not be found.',
    405: 'The HTTP method used is not allowed for the resource.',
    406: 'The requested resource cannot generate acceptable content.',
    407: 'The client must authenticate with a proxy.',
    408: 'The server timed out waiting for the request.',
    409: 'The request conflicts with the current state of the resource.',
    410: 'The resource requested has been permanently removed.',
    411: 'The Content-Length header is required for the request.',
    412: 'The server does not meet one of the preconditions specified in the request.',
    413: 'The request payload is too large for the server to process.',
    414: 'The URI provided is too long for the server to process.',
    415: "The request entity's media type is unsupported by the server.",
    416: 'The client requested a range that is not satisfiable by the server.',
    417: "The server cannot meet the expectations indicated in the request's headers.",
    418: 'The server refuses the attempt to brew coffee with a teapot.',
    421: 'The request was directed at a server that cannot produce a response.',
    422: 'The server understands the content type and request, but it cannot process it.',
    423: 'The resource that is being accessed is locked.',
    424: 'The request failed due to failure of a previous request.',
    426: 'The server requires the client to upgrade to a different protocol.',
    428: 'The origin server requires the request to be conditional.',
    429: 'The user has sent too many requests in a given time.',
    431: 'The server is unwilling to process the request due to large headers.',
    451: 'The resource is unavailable for legal reasons.',
    // Server Error Responses (500 – 599)
    500: 'The server encountered an internal error and cannot process the request.',
    501: 'The server does not support the functionality required to fulfill the request.',
    502: 'The server received an invalid response from an upstream server.',
    503: 'The server is currently unable to handle the request due to overload or maintenance.',
    504: 'The server did not receive a timely response from an upstream server.',
    505: 'The server does not support the HTTP version used in the request.',
    506: 'The server has an internal configuration error.',
    507: 'The server is unable to store the representation needed to complete the request.',
    508: 'The server detected an infinite loop while processing the request.',
    510: 'Further extensions to the request are required.',
    511: 'The client needs to authenticate to gain network access.',
} as const;

export const ResponseStatusKR: Record<number, string> = {
    // Informational Responses (100 – 199)
    100: '클라이언트가 요청을 계속 진행해야 합니다.',
    101: '서버가 프로토콜을 전환 중입니다.',
    102: '서버가 요청을 수신하고 처리 중입니다.',
    103: '서버가 자원을 미리 로드하도록 초기 힌트를 전송 중입니다.',
    // Successful Responses (200 – 299)
    200: '요청이 성공적으로 처리되었습니다.',
    201: '요청이 성공적으로 처리되었고, 새로운 리소스가 생성되었습니다.',
    202: '요청이 수락되었지만 아직 처리되지 않았습니다.',
    203: '요청이 성공적으로 처리되었으나, 정보는 원 서버로부터 온 것이 아닐 수 있습니다.',
    204: '요청이 성공적으로 처리되었으나, 반환할 내용이 없습니다.',
    205: '클라이언트가 문서 보기를 재설정해야 합니다.',
    206: '서버가 자원의 일부만을 전송하고 있습니다.',
    207: '독립적인 여러 작업의 상태입니다.',
    208: '해당 리소스는 이미 보고되었습니다.',
    226: '서버가 인스턴스 조작을 통해 요청을 처리했습니다.',
    // Redirection Messages (300 – 399)
    300: '해당 리소스에 대해 여러 가지 선택 사항이 있습니다.',
    301: '리소스가 새로운 영구 URI로 이동되었습니다.',
    302: '리소스가 임시로 다른 URI에 있습니다.',
    303: '클라이언트는 다른 URI에서 리소스를 요청해야 합니다.',
    304: '리소스가 마지막 요청 이후로 수정되지 않았습니다.',
    305: '(사용되지 않음) 프록시를 통해서만 요청할 수 있습니다.',
    307: '리소스가 임시로 다른 URI에 있지만, HTTP 메서드는 변경되지 않아야 합니다.',
    308: '리소스가 영구적으로 다른 URI로 이동되었습니다.',
    // Client Error Responses (400 – 499)
    400: '클라이언트 오류로 인해 요청을 처리할 수 없습니다.',
    401: '인증이 필요하며, 인증이 실패했거나 제공되지 않았습니다.',
    402: '요청을 처리하기 위해 결제가 필요합니다.',
    403: '서버가 요청을 거부했습니다.',
    404: '요청한 리소스를 찾을 수 없습니다.',
    405: '리소스에 대해 허용되지 않은 HTTP 메서드입니다.',
    406: '요청한 리소스는 허용할 수 있는 콘텐츠를 생성할 수 없습니다.',
    407: '클라이언트는 프록시에서 인증해야 합니다.',
    408: '서버가 요청을 기다리는 중 타임아웃되었습니다.',
    409: '현재 서버 상태와 충돌하는 요청입니다.',
    410: '요청한 리소스가 영구적으로 삭제되었습니다.',
    411: '요청에 필요한 Content-Length 헤더가 없습니다.',
    412: '요청의 사전 조건을 서버가 충족하지 못했습니다.',
    413: '요청 페이로드가 너무 커서 서버가 처리할 수 없습니다.',
    414: '제공된 URI가 너무 길어 서버에서 처리할 수 없습니다.',
    415: '요청 엔터티의 미디어 타입이 서버에서 지원되지 않습니다.',
    416: '클라이언트가 요청한 범위를 서버에서 만족시킬 수 없습니다.',
    417: '서버가 요청의 Expect 헤더에 명시된 요구 사항을 충족할 수 없습니다.',
    418: '서버가 커피를 만들지 않기 위해 차 주전자입니다.',
    421: '요청이 응답을 생성할 수 없는 서버로 전송되었습니다.',
    422: '서버가 요청을 이해했으나, 처리할 수 없습니다.',
    423: '접근하려는 리소스가 잠겨 있습니다.',
    424: '이전 요청이 실패하여 해당 요청도 실패했습니다.',
    426: '서버는 클라이언트가 다른 프로토콜로 업그레이드해야 한다고 요구합니다.',
    428: '서버는 조건부 요청을 요구합니다.',
    429: '클라이언트가 너무 많은 요청을 보냈습니다.',
    431: '서버는 헤더가 너무 커서 요청을 처리할 수 없습니다.',
    451: '법적인 이유로 리소스에 접근할 수 없습니다.',
    // Server Error Responses (500 – 599)
    500: '서버에 내부 오류가 발생하여 요청을 처리할 수 없습니다.',
    501: '서버가 요청에 필요한 기능을 지원하지 않습니다.',
    502: '서버가 상위 서버로부터 잘못된 응답을 받았습니다.',
    503: '서버가 현재 과부하 상태이거나 유지보수 중이어서 요청을 처리할 수 없습니다.',
    504: '서버가 상위 서버로부터 적절한 응답을 제때 받지 못했습니다.',
    505: '서버가 요청에 사용된 HTTP 버전을 지원하지 않습니다.',
    506: '서버 구성 오류가 발생했습니다.',
    507: '서버가 요청을 완료하는 데 필요한 저장소를 확보할 수 없습니다.',
    508: '서버가 요청을 처리하는 동안 무한 루프를 감지했습니다.',
    510: '요청을 완료하기 위해 추가 확장이 필요합니다.',
    511: '네트워크 접근을 위해 클라이언트가 인증해야 합니다.',
} as const;
